package ir.ramtung.tinyme.domain.entity;

public enum MatchingOutcome {
    EXECUTED,
    NOT_ENOUGH_CREDIT,
    NOT_ENOUGH_POSITIONS,
    MINIMUM_QUANTITY_INSUFFICIENT,
    CANT_UPDATE_MIN_QUANTITY,
    INACTIVE_ORDER_ENQUEUED,
    OPENING_PRICE_ANNOUNCEMENT,
    AUCTION_MATCH_COMPLETED
}
